services:
  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: andreylawyer/useragent-parser:v1.0
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

