# render.yaml

services:
  - name: spring-app
    type: web
    runtime: image
    image:
      url: andreylawyer/useragent-parser:v1.0
    plan: starter
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb://mongo:27017/useragentdb
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: "6379"
    healthCheckPath: /
    regions: oregon
    autoDeploy: true
    dependsOn:
      - name: mongodb
      - name: redis
    ports:
      - 8080

  - name: mongodb
    type: pserv
    runtime: docker
    image:
      url: mongo:8.0
    plan: starter
    envVars: []
    autoDeploy: true
    regions: oregon
    volumes:
      - name: mongo_data
        mountPath: /data/db
    ports:
      - 27017

  - name: redis
    type: redis
    runtime: docker
    image:
      url: redis:7.4-alpine
    plan: starter
    autoDeploy: true
    regions: oregon
    ports:
      - 6379

volumes:
  - name: mongo_data
    path: /data/db

