services:
  - name: spring-app
    type: web
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: "" # Приложение уже собрано
    startCommand: "java -jar app.jar"
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb://mongo:27017/useragentdb
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: "6379"
    dependsOn:
      - redis
      - mongo
    plan: free
    healthCheckPath: "/" # Укажите путь для проверки состояния вашего приложения
    region: frankfurt # Укажите предпочтительный регион Render

  - name: redis
    type: redis
    plan: free

  - name: mongo
    type: web
    env: docker
    dockerfilePath: ""
    startCommand: "mongod --bind_ip_all"
    image: mongo:8.0
    plan: free
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: useragentdb

