services:
  - type: web
    name: useragent-parser
    env: docker
    plan: free
    docker:
      image: andreylawyer/useragent-parser:v1.0
      buildCommand: 'echo "Docker image already built"'
      startCommand: 'java -Dspring.data.mongodb.uri=mongodb://mongo:27017/useragentdb -jar app.jar'
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb://mongo:27017/useragentdb
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: '6379'
    waitFor:
      - mongo
      - redis

  - type: pserv
    name: mongo
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    docker:
      image: mongo:8.0
      restartPolicy: always
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: password
    ports:
      - "27017:27017"

  - type: redis-db
    name: redis
    env: docker
    autoDeploy: false
    disk:
     name: data
     mountPath: /var/lib/redis
    sizeGB: 10
    docker:
      image: redis:7.4-alpine
      restartPolicy: always
    ports:
        - "6379:6379"
