services:
  - name: spring-app
    type: web
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: "" # No build command since the image is ready
    startCommand: "java -jar app.jar"
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://<MONGO_USER>:<MONGO_PASSWORD>@<MONGO_CLUSTER>/<DB_NAME>
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: "6379"
    dependsOn:
      - redis
      - mongodb
    plan: free
    healthCheckPath: "/" # Define if your app has a specific health check endpoint
    region: oregon # Replace with a preferred Render region

  - name: redis
    type: redis
    plan: free

  - name: mongodb
    type: database
    databaseType: mongodb
    plan: free
    ipAllowList: # Ensure the spring-app service can connect
      - source: spring-app

